title: Mike Hourahine
email: mike@hourahine.net
twitter_username: mhourahine
github_username: mhourahine
description: >
  This is description of Mike... nice to meet you.

#build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
